
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalcBasic extends javax.swing.JFrame {
    LocalDate fechaActual = LocalDate.now();
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE, MMM YYYY");
    String fech = fechaActual.format(formato);
    
    //variables globales
    int valor1, valor2;
    public jfrmCalcBasic() {
        initComponents();
        jtxtfecha.setText(fech);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblresultado = new javax.swing.JLabel();
        jtxtfecha = new javax.swing.JTextField();
        jtxtnum1 = new javax.swing.JTextField();
        jtxtnum2 = new javax.swing.JTextField();
        jbtnsuma = new javax.swing.JButton();
        jbtnresta = new javax.swing.JButton();
        jbtndivision = new javax.swing.JButton();
        jbtnmultiplicacion = new javax.swing.JButton();
        jbtnnum2 = new javax.swing.JButton();
        jbtnnum1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("Calculadora");

        jLabel2.setText("Escriba un valor númerico:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Digite otro valor númerico:");

        jlblresultado.setText("Resultado:");

        jtxtfecha.setEditable(false);

        jtxtnum1.setText("0");

        jtxtnum2.setText("0");

        jbtnsuma.setText("+");
        jbtnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsumaActionPerformed(evt);
            }
        });

        jbtnresta.setText("-");
        jbtnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrestaActionPerformed(evt);
            }
        });

        jbtndivision.setText("/");
        jbtndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivisionActionPerformed(evt);
            }
        });

        jbtnmultiplicacion.setText("*");
        jbtnmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiplicacionActionPerformed(evt);
            }
        });

        jbtnnum2.setText("+1");
        jbtnnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnum2ActionPerformed(evt);
            }
        });

        jbtnnum1.setText("+1");
        jbtnnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnum1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlblresultado)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnsuma)
                        .addGap(28, 28, 28)
                        .addComponent(jbtnresta)
                        .addGap(26, 26, 26)
                        .addComponent(jbtndivision)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnnum1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnnum2))
                    .addComponent(jbtnmultiplicacion)
                    .addComponent(jtxtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnnum1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnnum2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jlblresultado)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnmultiplicacion)
                    .addComponent(jbtndivision)
                    .addComponent(jbtnresta)
                    .addComponent(jbtnsuma))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsumaActionPerformed
        // TODO add your handling code here:
        int num1, num2;
        num1=Integer.parseInt(jtxtnum1.getText());
        num2=Integer.parseInt(jtxtnum2.getText());
        int suma=num1+num2;
        jlblresultado.setText(String.valueOf("Resultado: "+suma));
    }//GEN-LAST:event_jbtnsumaActionPerformed

    private void jbtnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrestaActionPerformed
        // TODO add your handling code here:
        int num1, num2;
        num1=Integer.parseInt(jtxtnum1.getText());
        num2=Integer.parseInt(jtxtnum2.getText());
        int resta=num1-num2;
        jlblresultado.setText(String.valueOf("Resultado: "+resta));
    }//GEN-LAST:event_jbtnrestaActionPerformed

    private void jbtndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivisionActionPerformed
        // TODO add your handling code here:
        int num1, num2;
        num1=Integer.parseInt(jtxtnum1.getText());
        num2=Integer.parseInt(jtxtnum2.getText());
        int division=num1/num2;
        jlblresultado.setText(String.valueOf("Resultado: "+division));
    }//GEN-LAST:event_jbtndivisionActionPerformed

    private void jbtnmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplicacionActionPerformed
        // TODO add your handling code here:
        int num1, num2;
        num1=Integer.parseInt(jtxtnum1.getText());
        num2=Integer.parseInt(jtxtnum2.getText());
        int multiplicacion=num1*num2;
        jlblresultado.setText(String.valueOf("Resultado: "+multiplicacion));
    }//GEN-LAST:event_jbtnmultiplicacionActionPerformed

    private void jbtnnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnum1ActionPerformed
        // TODO add your handling code here:
        valor1=Integer.parseInt(jtxtnum1.getText());
        //Contador
        valor1=valor1+1;
        jtxtnum1.setText(String.valueOf(valor1));
    }//GEN-LAST:event_jbtnnum1ActionPerformed

    private void jbtnnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnum2ActionPerformed
        // TODO add your handling code here:
        valor2=Integer.parseInt(jtxtnum2.getText());
        //Contador
        valor2=valor2+1;
        jtxtnum2.setText(String.valueOf(valor2));
    }//GEN-LAST:event_jbtnnum2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalcBasic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtndivision;
    private javax.swing.JButton jbtnmultiplicacion;
    private javax.swing.JButton jbtnnum1;
    private javax.swing.JButton jbtnnum2;
    private javax.swing.JButton jbtnresta;
    private javax.swing.JButton jbtnsuma;
    private javax.swing.JLabel jlblresultado;
    private javax.swing.JTextField jtxtfecha;
    private javax.swing.JTextField jtxtnum1;
    private javax.swing.JTextField jtxtnum2;
    // End of variables declaration//GEN-END:variables
}
